title: Jinzhang Nan's Homepage
page-top-title: Jinzhang Nan
top-section-bg-text: Applied Statistics
home-subtitle: Jinzhang Nan &ensp;|&ensp;南锦璋
copyright-text: '&copy; Jinzhang Nan 2023-2025. All Rights Reserved.'
